### ISSUE TITLE
Add and edit metadata fields

### ISSUE THREAD

**Issue by niklas-may** [robinpyon/sanity-plugin-media#15]
It Would be great if you could add metadata to assets from within the media library.
This would come in handy if you need to display copyright information of an image on the frontend.

Do you think this is possible with the way sanity handles images? 
Would be happy to help implementing this feature.

**Comment by robinpyon** [comment]
This is now possible in 1.0! Right now, `title`, `description` and `altText` fields are editable directly on both `sanity.imageAsset` and `sanity.fileAsset`

**Comment by fabien** [comment]
@robinpyon any plans of allowing additional fields (defined in a global config) set by the developer?

**Comment by robinpyon** [comment]
@fabien it's something I've definitely been considering

I was looking to only expose this when it'd be possible to support all native Sanity schema types (with the exception of `file` and `image` of course!) - so you'd be able to define custom fields in the exact same way you do with documents. I don't have an ETA here i'm afraid!

**Comment by danielmahal** [comment]
> I was looking to only expose this when it'd be possible to support all native Sanity schema types (with the exception of `file` and `image` of course!) - so you'd be able to define custom fields in the exact same way you do with documents. I don't have an ETA here i'm afraid!

This is a feature we would love to see for a couple of projects that we're currently working on. Our immediate use case would be alt text for multilingual sites, and authoring credits as an array of references.

Do you have any ideas on how this feature could be implemented? Perhaps I could look into it and contribute with a pull request, if that’s something you would be open to?

Alternatively, could you be interested in looking into this with financial support from us at internetfriendsforever?

**Comment by robinpyon** [comment]
@danielmahal 

> Do you have any ideas on how this feature could be implemented?

The current asset form elements – despite using `@sanity/ui` – aren't actually using Sanity's native `FormBuilder` and essentially those string, text and tag select fields have been hand rolled, though I've tried to make them look as native as possible.

As such, they don't take advantage of Sanity's validation schema or other features like _Presence_, or _Review Changes_ , and adding other input fields (such as single or array references) is something that would need to be manually built out.

I haven't yet time to fully investigate this, but my understanding is that the `FormBuilder` API isn't something that you can yet easily use outside of a custom input component, and I'd consider holding out until that's the case – I'd like to lean on it as much as possible!

Furthermore, I think that there's a strong argument for being able to define custom fields for `sanity.imageAsset` outside of the plugin – since it could open avenues for those fields to be editable directly from the desk, without needing to go via the media plugin. I think this is something that could be useful for all users regardless of this plugin, so that's something I'd like to try run by the Sanity team first!

That said, if you need the ability to add additional string / text fields to the asset edit form _right now_, that should be straightforward and I can help you navigate that in a separate fork – though you'd be responsible for creating that reference input!

**Comment by barbogast** [comment]
@robinpyon First of all, awesome plugin, thanks a lot ❤️ 

You're raising points that I've also been thinking about, so I thought I just post my thoughts, maybe it's helpful.

> I haven't yet time to fully investigate this, but my understanding is that the FormBuilder API isn't something that you can yet easily use outside of a custom input component, and I'd consider holding out until that's the case – I'd like to lean on it as much as possible!
I've also been looking into this and came to a similar conclusion (although I didn't dig too deep, maybe it is possible after all). In any case it would be super powerful if we could cobble together custom forms by reusing the input elements of the studio, together with live updates, validation, presence and so on. My use case is to build one form which allows to edit the same field(s) in multiple documents. Being able to reuse the form field infrastructure of the studio would be super powerful.

> Furthermore, I think that there's a strong argument for being able to define custom fields for sanity.imageAsset outside of the plugin – since it could open avenues for those fields to be editable directly from the desk, without needing to go via the media plugin. I think this is something that could be useful for all users regardless of this plugin, so that's something I'd like to try run by the Sanity team first!
Again, I totally agree. Being able to add custom metadata to the asset (rather than the document the asset is included in) would be super powerful. I might even go further and say that not being able to do that goes a bit against the spirit of Sanity of being able to arbitrarily compose the schema.

To work around the issue I'll not work with `type: 'image'` directly but instead encapsulate each image into a document. This allows to use all the good stuff (arbitrary fields being stored _with_ the asset, showing assets in the structure builder, referencing assets, ...). 

The longer I think about it the more I realise that that actually is the "right solution", or am I missing something? 

The big downside is that the UX is not as pretty: Selecting images in a gallery is nicer than a list of references, and creating a doc is a bit more cumbersome, and so on. But those issues can be fixed, for example by adding a custom image source that uses a certain document type as the image source.

And I feel that it's easier to fix the UX issues than having to work around shortcomings on the schema level.

To make this reality we'd need to:
- adapt sanity-media-plugin to (optionally) work with assets wrapped into document instead of plain assets
- create a custom image source which allows to conveniently select an image from a certain document type
- optional: create a component for the structure builder that shows documents as a gallery

I don't want to propose to just go ahead and turn sanity-media-plugin on its head 😂, I'm rather just thinking out aloud at this point.
