### ISSUE TITLE
Sorting alphabetically getting thrown by the dash character.

### ISSUE THREAD

**Issue by Ojay** [robinpyon/sanity-plugin-media#33]
Hi there,

So we have a naming structure like `continent-country-region.jpg` and when sorting alphabetically the capitalisation seems to be throwing it off. See attached image.

<img width="426" alt="Screenshot 2021-04-08 at 21 57 38" src="https://user-images.githubusercontent.com/1914101/114095635-8f8fca80-98b5-11eb-9e7a-477305937ddc.png">

Can you replicate this? Any way around it?

Thanks so much!

Mark

**Comment by Ojay** [comment]
Dude, I'm so sorry... wrong Sanity Media repo! 😂

**Comment by Ojay** [comment]
So, switched to use this media tool thanks to the batch upload working a lot smoother than the alternative. Randomly a similar sorting issues occurs with this plugin too, this time relating to capitalisation. I've updated the original post to reflect this issue.

Thanks

**Comment by robinpyon** [comment]
Hey @Ojay,

This behaviour (whilst not always intuitive) is intentional!

All results are sorted via GROQ, which itself uses [case-insensitive string comparison](https://www.sanity.io/docs/groq-operators#80749b4f431a). This means that uppercase characters are placed before lowercase ones – which is probably different to what your OS might be showing.

Here's an example with your dataset in the GROQ playground: https://groq.dev/wfT2FZWGIYhPvQYr1hNkQg (click the play button to see how GROQ orders that data). This is also the default behaviour of `sort()` in JavaScript.

AFAIK there isn't a way to use case-insensitive ordering right now, not at least until it's natively supported in GROQ – sorry! (the alternative would be to sort on the client and over-fetch, which probably won't be tenable on larger datasets)

**Comment by Ojay** [comment]
Brilliant explanation, thanks... didn't realise that was the case with `sort()`.

Cheers and top plugin btw!
