### ISSUE TITLE
Asset URL display/copy

### ISSUE THREAD

**Issue by tkatchenko** [robinpyon/sanity-plugin-media#40]
Hi there, I was wondering if there's a way to display/copy the asset URL? This is useful as a work around if the asset, say a PDF, needs to be linked to multiple times due to Sanity Studio not having custom asset sources for files.

**Comment by robinpyon** [comment]
Hey @tkatchenko – it's possible in the latest version of this plugin (currently `1.3.1`)

When you click into an asset, scroll down and you should see buttons to download and copy the asset URL to your clipboard, e.g.

![image](https://user-images.githubusercontent.com/209129/117949370-f7e52800-b309-11eb-851a-e493d20602b1.png)

This isn't clear in the image in the README (since it's below the fold), so I'll update that!

**Comment by tkatchenko** [comment]
Oh amazing, thanks so much!
